# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---

attribution:
  country: 'Our World in Data'
  source_name: 'Our World in Data'
  main_link: 'www.OurWorldInData.org'
  data_link: 'https://ourworldindata.org/coronavirus'
  description: 'Data from Our World in Data includes Deaths, Testing, Cases, and Government responses for every country in the world.'
license:
  name: 'Creative Commons Attribution 4.0 International'
  file: 'docs/license_files/cc-by-4.0'
  link: 'https://creativecommons.org/licenses/by/4.0/'
cc-by-sa: False
approved: True
